// Code generated by ogen, DO NOT EDIT.
package oas

type GetDepositsRes interface {
	getDepositsRes()
}

type GetIncomeHistoryRes interface {
	getIncomeHistoryRes()
}

type GetIncomeRes interface {
	getIncomeRes()
}

type GetSyncRes interface {
	getSyncRes()
}

type GetWithdrawalStatusRes interface {
	getWithdrawalStatusRes()
}

type MakeNewDepositRes interface {
	makeNewDepositRes()
}

type SendWithdrawalRes interface {
	sendWithdrawalRes()
}

type ServiceJettonWithdrawalRes interface {
	serviceJettonWithdrawalRes()
}

type ServiceTonWithdrawalRes interface {
	serviceTonWithdrawalRes()
}
