// Code generated by ogen, DO NOT EDIT.
package oas

type GetAddressesRes interface {
	getAddressesRes()
}

type GetIncomeHistoryRes interface {
	getIncomeHistoryRes()
}

type GetIncomeRes interface {
	getIncomeRes()
}

type GetNewAddressRes interface {
	getNewAddressRes()
}

type GetSyncRes interface {
	getSyncRes()
}

type GetWithdrawalStatusRes interface {
	getWithdrawalStatusRes()
}

type SendWithdrawalRes interface {
	sendWithdrawalRes()
}

type ServiceJettonWithdrawalRes interface {
	serviceJettonWithdrawalRes()
}

type ServiceTonWithdrawalRes interface {
	serviceTonWithdrawalRes()
}
