###
POST {{url}}/v1/address/new
Authorization: Bearer {{token}}
Content-Type: application/json

{"user_id": "TestUser", "currency": "TON"}

###
POST {{url}}/v1/address/new
Authorization: Bearer {{token}}
Content-Type: application/json

{"user_id": "TestUser", "currency": "TGR"}

###
GET {{url}}/v1/address/all?user_id=TestUser
Authorization: Bearer {{token}}

###
GET {{url}}/v1/income?user_id=TestUser
Authorization: Bearer {{token}}

###
GET {{url}}/v1/deposit/history?user_id=TestUser&currency=TON&limit=3&offset=0&sort_order=asc
Authorization: Bearer {{token}}

###
POST {{url}}/v1/withdrawal/send
Authorization: Bearer {{token}}
Content-Type: application/json

{"user_id": "TestUser", "query_id": "1", "currency": "TON", "amount":  200000000, "destination": "kQBFETbGASx3-6QYpPuQAKQM1s32AfSkWzbsADqt3bKDlN1A", "comment":  "test_ton_withdrawal"}

###
POST {{url}}/v1/withdrawal/send
Authorization: Bearer {{token}}
Content-Type: application/json

{"user_id": "TestUser", "query_id": "2", "currency": "TGR", "amount":  1000, "destination": "kQBFETbGASx3-6QYpPuQAKQM1s32AfSkWzbsADqt3bKDlN1A", "comment":  "test_jetton_withdrawal"}

###
POST {{url}}/v1/withdrawal/send
Authorization: Bearer {{token}}
Content-Type: application/json

{"user_id": "TestUser", "query_id": "3", "currency": "TON", "amount":  1000, "destination": "kQBFETbGASx3-6QYpPuQAKQM1s32AfSkWzbsADqt3bKDlN1A", "binary_comment":  "9fe7_"}


###
POST {{url}}/v1/withdrawal/service/jetton
Authorization: Bearer {{token}}
Content-Type: application/json

{"owner": "0QCdsj-u39qVlfYdpPKuAY0hTe5VIsiJcpB5Rx4tOUOyBFhL", "jetton_master": "kQAbMQzuuGiCne0R7QEj9nrXsjM7gNjeVmrlBZouyC-SCALE"}

###
POST {{url}}/v1/withdrawal/service/ton
Authorization: Bearer {{token}}
Content-Type: application/json

{"from": "0QAOp2OZwWdkF5HhJ0WVDspgh6HhpmHyQ3cBuBmfJ4q_AIVe"}

###
GET {{url}}/v1/withdrawal/status?id=2
Authorization: Bearer {{token}}

###
GET {{url}}/v1/system/sync

###
GET {{url}}/metrics

###
GET {{url}}//v1/deposit/income?tx_hash=54e61136c33b94372030de8c7d02bc23a60e3de7cfad46f26258e8e722dc66b1
Authorization: Bearer {{token}}

###
GET {{url}}//v1/balance?currency=TON&address=kQAbMQzuuGiCne0R7QEj9nrXsjM7gNjeVmrlBZouyC-SCALE
Authorization: Bearer {{token}}

###
GET {{url}}//v1/balance?currency=TON
Authorization: Bearer {{token}}

###
GET {{url}}//v1/resolve?domain=wallet.ton
Authorization: Bearer {{token}}
