{
 "title": "Payments",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Last blocks",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  shard, seqno, gen_utime\nFROM payments.block_data\nORDER BY seqno desc\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Withdrawal requests",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  query_id, processing, processed, amount, currency,comment\nFROM payments.withdrawal_requests\nORDER BY query_id DESC"
    }
   ]
  },
  {
   "title": "External imcomes",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  utime, amount, coalesce(tw.subwallet_id, jw.subwallet_id) as subwallet_id, coalesce(currency, 'TON') as currency, comment\nFROM\n  payments.external_incomes ei\nLEFT JOIN payments.ton_wallets tw ON ei.deposit_address = tw.address \nLEFT JOIN payments.jetton_wallets jw ON ei.deposit_address = jw.address\n"
    }
   ]
  },
  {
   "title": "Wallets",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  tw.subwallet_id, tw.user_id, tw.type as ton_type,jw.type as jetton_type, coalesce(currency, 'TON') as Currency\nFROM payments.ton_wallets tw\nLEFT JOIN payments.jetton_wallets jw ON tw.subwallet_id = jw.subwallet_id\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{})/60"
    }
   ]
  },
  {
   "title": "External withdrawals",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  ew.query_id,wr.amount,wr.currency,confirmed,failed,processed_at \nFROM\n  payments.external_withdrawals ew\nLEFT JOIN payments.withdrawal_requests wr ON ew.query_id = wr.query_id\nWHERE wr.is_internal=false\n\n  \n"
    }
   ]
  },
  {
   "title": "Internal withdrawals",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  memo,amount,coalesce(jw.currency, 'TON') as currency,coalesce(tw.subwallet_id, jw.subwallet_id) as from, finished_at, failed\nFROM\n  payments.internal_withdrawals iw\nLEFT JOIN payments.ton_wallets tw ON iw.from_address = tw.address \nLEFT JOIN payments.jetton_wallets jw ON iw.from_address = jw.address  \n\n"
    }
   ]
  },
  {
   "title": "Wallets balances",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "payer_wallet_balance{}/1000000000",
     "legendFormat": "Payer/{{currency}}"
    },
    {
     "expr": "hot_wallet_balance{}/1000000000",
     "legendFormat": "Hot/{{currency}}"
    },
    { "expr": "total_balance{}/1000000000", "legendFormat": "Tot/{{currency}}" }
   ]
  },
  {
   "title": "Losses",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_losses{}/1000000000", "legendFormat": "{{currency}}" }
   ]
  },
  {
   "title": "Cold wallet withdrawals",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  ew.query_id,wr.amount,wr.currency,confirmed,failed,processed_at \nFROM\n  payments.external_withdrawals ew\nLEFT JOIN payments.withdrawal_requests wr ON ew.query_id = wr.query_id\nWHERE wr.is_internal=true\n"
    }
   ]
  },
  {
   "title": "Internal incomes",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  memo,amount,coalesce(jw.currency, 'TON') as currency,coalesce(tw.subwallet_id, jw.subwallet_id) as from\nFROM\n  payments.internal_incomes ii\nLEFT JOIN payments.ton_wallets tw ON ii.deposit_address = tw.address \nLEFT JOIN payments.jetton_wallets jw ON ii.deposit_address = jw.address  \n"
    }
   ]
  },
  {
   "title": "Deposit balances",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "deposit_wallet_balance{}", "legendFormat": "{{currency}}  {{address}} " }
   ]
  },
  {
   "title": "Deposit side balances",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  coalesce(tw.subwallet_id, jw.subwallet_id) as subwallet_id, SUM(amount) as total_amount, coalesce(jw.currency, 'TON') as currency\nFROM\n  payments.external_incomes ei\nLEFT JOIN payments.ton_wallets tw ON ei.deposit_address = tw.address \nLEFT JOIN payments.jetton_wallets jw ON ei.deposit_address = jw.address\nGROUP BY ei.deposit_address, tw.subwallet_id, jw.subwallet_id, jw.currency\n\n"
    }
   ]
  },
  {
   "title": "Hot side deposit balances",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  coalesce(tw.subwallet_id, jw.subwallet_id) as subwallet_id, SUM(amount) as total_amount, coalesce(jw.currency, 'TON') as currency\nFROM\n  payments.internal_incomes ii\nLEFT JOIN payments.ton_wallets tw ON ii.deposit_address = tw.address \nLEFT JOIN payments.jetton_wallets jw ON ii.deposit_address = jw.address\nGROUP BY ii.deposit_address, tw.subwallet_id, jw.subwallet_id, jw.currency\n\n"
    }
   ]
  }
 ]
}